# Generated by Django 4.0.3 on 2023-07-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_remove_appointment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='picture_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
