# Generated by Django 4.0.3 on 2023-07-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_technician_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='picture_url',
            field=models.URLField(max_length=20000, null=True),
        ),
    ]
