# Generated by Django 4.0.3 on 2023-08-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0012_alter_technician_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_favorite',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
