# Generated by Django 4.0.3 on 2023-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0003_alter_vehiclemodel_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='dealer_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobile',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobile',
            name='type',
            field=models.CharField(choices=[('used', 'used'), ('new', 'new')], max_length=30, null=True),
        ),
    ]
